[rospy.client][INFO] 2012-12-15 18:02:37,447: init_node, name[/depth_detection], pid[13015]
[xmlrpc][INFO] 2012-12-15 18:02:37,447: XML-RPC server binding to 0.0.0.0
[xmlrpc][INFO] 2012-12-15 18:02:37,448: Started XML-RPC server [http://pc:39682/]
[rospy.init][INFO] 2012-12-15 18:02:37,448: ROS Slave URI: [http://pc:39682/]
[rospy.impl.masterslave][INFO] 2012-12-15 18:02:37,449: _ready: http://pc:39682/
[xmlrpc][INFO] 2012-12-15 18:02:37,449: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2012-12-15 18:02:37,450: Registering with master node http://localhost:11311
[rospy.init][INFO] 2012-12-15 18:02:37,549: registered with master
[rospy.rosout][INFO] 2012-12-15 18:02:37,594: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-15 18:02:37,598: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-15 18:02:37,600: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2012-12-15 18:02:51,303: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2b9da70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 282, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:02:54,111: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2b9da70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 282, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rosout][ERROR] 2012-12-15 18:02:55,644: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2b9da70>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 282, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 107, in get_contours
    cont[0] = DepthDetector.merge_contours(cont[0])
TypeError: 'tuple' object does not support item assignment

[rospy.core][INFO] 2012-12-15 18:02:55,674: signal_shutdown [signal-2]
[rospy.impl.masterslave][INFO] 2012-12-15 18:02:55,685: signal-2
[rospy.core][INFO] 2012-12-15 18:02:55,802: signal_shutdown [atexit]
