[rospy.client][INFO] 2012-12-14 17:28:00,121: init_node, name[/depth_detection], pid[26232]
[xmlrpc][INFO] 2012-12-14 17:28:00,121: XML-RPC server binding to 0.0.0.0
[xmlrpc][INFO] 2012-12-14 17:28:00,123: Started XML-RPC server [http://pc:36936/]
[rospy.init][INFO] 2012-12-14 17:28:00,123: ROS Slave URI: [http://pc:36936/]
[rospy.impl.masterslave][INFO] 2012-12-14 17:28:00,123: _ready: http://pc:36936/
[xmlrpc][INFO] 2012-12-14 17:28:00,124: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2012-12-14 17:28:00,124: Registering with master node http://localhost:11311
[rospy.init][INFO] 2012-12-14 17:28:00,223: registered with master
[rospy.rosout][INFO] 2012-12-14 17:28:00,261: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-14 17:28:00,263: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-14 17:28:00,266: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2012-12-14 17:28:08,597: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:08,606: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:08,635: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:08,660: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:08,696: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:08,729: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:08,764: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:08,799: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:08,832: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:08,872: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:08,908: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:08,928: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:08,966: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:09,003: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:09,041: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:09,064: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:09,100: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:09,132: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:09,169: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:09,202: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:09,231: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:09,263: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:09,301: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rosout][ERROR] 2012-12-14 17:28:09,324: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rospy.core][INFO] 2012-12-14 17:28:09,354: signal_shutdown [signal-2]
[rosout][ERROR] 2012-12-14 17:28:09,365: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x39198c0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 203, in depth_cb
    self.filter_edge_depth(img)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 179, in filter_edge_depth
    h, w, _ = img.shape
ValueError: need more than 2 values to unpack

[rospy.impl.masterslave][INFO] 2012-12-14 17:28:09,368: signal-2
[rospy.core][INFO] 2012-12-14 17:28:09,983: signal_shutdown [atexit]
