[rospy.client][INFO] 2012-12-15 19:43:59,199: init_node, name[/depth_detection], pid[5539]
[xmlrpc][INFO] 2012-12-15 19:43:59,199: XML-RPC server binding to 0.0.0.0
[xmlrpc][INFO] 2012-12-15 19:43:59,200: Started XML-RPC server [http://pc:58320/]
[rospy.init][INFO] 2012-12-15 19:43:59,200: ROS Slave URI: [http://pc:58320/]
[rospy.impl.masterslave][INFO] 2012-12-15 19:43:59,200: _ready: http://pc:58320/
[xmlrpc][INFO] 2012-12-15 19:43:59,200: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2012-12-15 19:43:59,201: Registering with master node http://localhost:11311
[rospy.init][INFO] 2012-12-15 19:43:59,300: registered with master
[rospy.rosout][INFO] 2012-12-15 19:43:59,332: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-15 19:43:59,335: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-15 19:43:59,336: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][ERROR] 2012-12-15 19:44:09,721: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2414a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 289, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 116, in get_contours
    brect = cv2.boundingRect(c)
error: /tmp/buildd/libopencv-2.3.1+svn6514+branch23/modules/imgproc/src/contours.cpp:1664: error: (-215) points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S) in function boundingRect


[rosout][ERROR] 2012-12-15 19:44:09,798: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2414a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 289, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 116, in get_contours
    brect = cv2.boundingRect(c)
error: /tmp/buildd/libopencv-2.3.1+svn6514+branch23/modules/imgproc/src/contours.cpp:1664: error: (-215) points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S) in function boundingRect


[rosout][ERROR] 2012-12-15 19:44:09,921: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2414a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 289, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 116, in get_contours
    brect = cv2.boundingRect(c)
error: /tmp/buildd/libopencv-2.3.1+svn6514+branch23/modules/imgproc/src/contours.cpp:1664: error: (-215) points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S) in function boundingRect


[rosout][ERROR] 2012-12-15 19:44:10,488: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2414a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 289, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 116, in get_contours
    brect = cv2.boundingRect(c)
error: /tmp/buildd/libopencv-2.3.1+svn6514+branch23/modules/imgproc/src/contours.cpp:1664: error: (-215) points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S) in function boundingRect


[rosout][ERROR] 2012-12-15 19:44:10,847: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2414a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 289, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 116, in get_contours
    brect = cv2.boundingRect(c)
error: /tmp/buildd/libopencv-2.3.1+svn6514+branch23/modules/imgproc/src/contours.cpp:1664: error: (-215) points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S) in function boundingRect


[rosout][ERROR] 2012-12-15 19:44:11,853: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2414a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 289, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 116, in get_contours
    brect = cv2.boundingRect(c)
error: /tmp/buildd/libopencv-2.3.1+svn6514+branch23/modules/imgproc/src/contours.cpp:1664: error: (-215) points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S) in function boundingRect


[rosout][ERROR] 2012-12-15 19:44:13,012: bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x2414a28>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 289, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 116, in get_contours
    brect = cv2.boundingRect(c)
error: /tmp/buildd/libopencv-2.3.1+svn6514+branch23/modules/imgproc/src/contours.cpp:1664: error: (-215) points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S) in function boundingRect


[rospy.core][INFO] 2012-12-15 19:44:13,265: signal_shutdown [signal-2]
[rospy.impl.masterslave][INFO] 2012-12-15 19:44:13,320: signal-2
[rospy.core][INFO] 2012-12-15 19:44:13,944: signal_shutdown [atexit]
